version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - 7700:7700
    volumes:
      - meilisearch-data:/data.ms
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=masterKey
      - MEILI_ENV=development
    
volumes:
  redis-data:
  meilisearch-data:
